# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

<% require 'socket'
   host = Socket.gethostname
   ports = { "development" => 3308,
             "test"        => 3308,
             "production"  => 3307 } 
   
%>

<% %w(development test production).each do |env| %>
<%= env %>:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pcbtr3_<%= env %>
  pool: 5
  username: pcbtr
  password: PcBtR
  host: <%= host %>
  port: <%= ports[env] %>

<% end %>
