# MySQL.  Versions 4.1 and 5.0 are recommended.
# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html


<% %w(development test production).each do |env| %>
<%= env %>:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pcbtr3_<%= env %>
  pool: 5
  username: root 
  password: connect
  host: localhost

<% end %>

<% %w(development test production).each do |env| %>
<%= "pcb_scheduler_" + env %>:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: pcbscheduler_<%= env %>
  pool: 5
  username: root 
  password: connect
  host: localhost

<% end %>

