# $Header$
--- 
cwd:         /hwnet/dtg_devel/web/boarddev/apps/pcbtr_production_branch/pcb_tracker/
port:        "8020"
user:        dtg
group:       dtg
environment: production
address:     127.0.0.1
pid_file:    /hwnet/dtg_devel/web/boarddev/apps/pcbtr_production_branch/pcb_tracker/shared/pids/mongrel.pid
servers:     4
