#!/bin/sh

#####################################################
# Used to retrieve the data used to upload BOMs to 
# TeamCenter
#####################################################
# $Id$
#####################################################

if [ $# = 0 ] ; then
    outfile=/hwnet/dtg_devel/tcbom/tracker_data.txt
else
    outfile=$1
fi

rooted=`echo $outfile | awk '/^\//{print}'`
if [ X$rooted = X ]; then
    #unrooted
    outfile=$PWD/$outfile
fi

cd /hwnet/dtg_devel/web/boarddev/applications/pcb_tracker

PATH=/usr/local/rbenv/shims:/usr/local/rbenv/bin:/usr/local/bin:/usr/bin:/bin bundle exec rake npi_bom:get_design_data RAILS_ENV=production > $outfile
#/usr/local/bin/rails runner -e production 'Design.bom_upload_data' > \
#    $outfile
