#!/bin/sh

#####################################################
# Used to retrieve the data used to upload BOMs to 
# TeamCenter
#####################################################
# $Id$
#####################################################

if [ "X$1" = "X" ]; then
  output_path=/hwnet/dtg_devel/tcbom/tracker_data.txt
else
  output_path=$1
fi

cd /hwnet/dtg_devel/web/etg/apps/pcbtr_production_branch/pcb_tracker

/usr/local/bin/ruby script/runner -e production 'Design.bom_upload_data' > \
    $output_path
