#!/bin/sh

#####################################################
# Used to provide cron with a mechanism for generating reviewer
# pings for the PCB Design Tracker
#####################################################
# $Id$
#####################################################

cd /hwnet/dtg_devel/web/boarddev/apps/pcbtr_development_branch/pcb_tracker

/usr/local/bin/ruby script/runner -e development 'Ping.send_summary'
