#!/bin/sh

#####################################################
# Used to provide cron with a mechanism for generating reviewer
# pings for the PCB Design Tracker
#####################################################
# $Id$
#####################################################

cd /hwnet/dtg_devel/web/etg/apps/pcb_tracker

/usr/local/bin/ruby script/runner 'Ping.send_message'
